<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DivisionsSeeder extends Seeder
{
    public function run(): void
    {
        $divisions = [
            [
                'code' => 'DIV-IT-02',
                'name' => 'IT Infrastructure',
                'parent' => 'IT Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Infrastruktur & server',
                'scope' => 'Jaringan, Cloud',
                'status' => 'Active',
                'manager' => 'Raka Saputra',
                'staff' => 5,
                'budget' => 600000000,
                'target_kpi' => 'Uptime 99%',
                'achievement' => '98%',
                'risk' => 'Server down',
                'system_role' => 'Infrastructure Admin',
                'access_rights' => 'Read, Update',
                'shift' => 'On Call',
                'operational_hour' => '24 Jam',
                'location' => 'Hybrid'
            ],
            [
                'code' => 'DIV-HRD-01',
                'name' => 'Recruitment',
                'parent' => 'HR Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Rekrutmen',
                'scope' => 'Hiring',
                'status' => 'Active',
                'manager' => 'Lina Aulia',
                'staff' => 3,
                'budget' => 250000000,
                'target_kpi' => 'Hiring tepat waktu',
                'achievement' => '90%',
                'risk' => 'Kandidat kurang',
                'system_role' => 'HR Officer',
                'access_rights' => 'Create, Read',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-FIN-01',
                'name' => 'Accounting',
                'parent' => 'Finance Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Keuangan',
                'scope' => 'Laporan',
                'status' => 'Active',
                'manager' => 'Siti Rahma',
                'staff' => 4,
                'budget' => 400000000,
                'target_kpi' => 'Akurasi laporan',
                'achievement' => '99%',
                'risk' => 'Human error',
                'system_role' => 'Finance',
                'access_rights' => 'Read, Update',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-FIN-02',
                'name' => 'Budgeting',
                'parent' => 'Finance Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Anggaran',
                'scope' => 'Budget',
                'status' => 'Active',
                'manager' => 'Arif Nugroho',
                'staff' => 3,
                'budget' => 300000000,
                'target_kpi' => 'Efisiensi biaya',
                'achievement' => '93%',
                'risk' => 'Over budget',
                'system_role' => 'Finance',
                'access_rights' => 'Read, Update',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-MKT-01',
                'name' => 'Digital Marketing',
                'parent' => 'Marketing Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Promosi digital',
                'scope' => 'Sosial Media',
                'status' => 'Active',
                'manager' => 'Deni Saputra',
                'staff' => 6,
                'budget' => 500000000,
                'target_kpi' => 'Engagement +30%',
                'achievement' => '27%',
                'risk' => 'Algoritma',
                'system_role' => 'Marketing',
                'access_rights' => 'Create, Read',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-MKT-02',
                'name' => 'Branding',
                'parent' => 'Marketing Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Branding',
                'scope' => 'Campaign',
                'status' => 'Active',
                'manager' => 'Alya Putri',
                'staff' => 4,
                'budget' => 450000000,
                'target_kpi' => 'Brand awareness',
                'achievement' => 'Baik',
                'risk' => 'Reputasi',
                'system_role' => 'Marketing',
                'access_rights' => 'Create, Read',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-OPS-01',
                'name' => 'Warehouse',
                'parent' => 'Operational Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Logistik',
                'scope' => 'Stok',
                'status' => 'Active',
                'manager' => 'Toni Wijaya',
                'staff' => 7,
                'budget' => 600000000,
                'target_kpi' => 'Akurasi stok',
                'achievement' => '98%',
                'risk' => 'Selisih stok',
                'system_role' => 'Operational',
                'access_rights' => 'Read, Update',
                'shift' => 'Shift',
                'operational_hour' => '08:00 - 16:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-OPS-02',
                'name' => 'Quality Control',
                'parent' => 'Operational Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Kontrol mutu',
                'scope' => 'Inspeksi',
                'status' => 'Active',
                'manager' => 'Rina Lestari',
                'staff' => 5,
                'budget' => 350000000,
                'target_kpi' => 'Reject <2%',
                'achievement' => '2.1%',
                'risk' => 'Kualitas',
                'system_role' => 'QC',
                'access_rights' => 'Read, Update',
                'shift' => 'Shift',
                'operational_hour' => '08:00 - 16:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-CS-01',
                'name' => 'Customer Service',
                'parent' => 'Service Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Layanan pelanggan',
                'scope' => 'Ticketing',
                'status' => 'Active',
                'manager' => 'Nanda Prakoso',
                'staff' => 10,
                'budget' => 700000000,
                'target_kpi' => 'SLA 95%',
                'achievement' => '94%',
                'risk' => 'Lonjakan tiket',
                'system_role' => 'Support',
                'access_rights' => 'Create, Read',
                'shift' => 'Shift',
                'operational_hour' => '24 Jam',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-LGL-01',
                'name' => 'Legal',
                'parent' => 'Legal Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Hukum',
                'scope' => 'Kontrak',
                'status' => 'Active',
                'manager' => 'Farhan Aziz',
                'staff' => 3,
                'budget' => 250000000,
                'target_kpi' => 'Compliance 100%',
                'achievement' => '100%',
                'risk' => 'Regulasi',
                'system_role' => 'Legal',
                'access_rights' => 'Read, Update',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-RND-01',
                'name' => 'Research & Development',
                'parent' => 'R&D Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Riset produk',
                'scope' => 'Analisis',
                'status' => 'Active',
                'manager' => 'Budi Santoso',
                'staff' => 6,
                'budget' => 900000000,
                'target_kpi' => 'Produk baru',
                'achievement' => '2',
                'risk' => 'Delay riset',
                'system_role' => 'Researcher',
                'access_rights' => 'Create, Read',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-ADM-01',
                'name' => 'General Admin',
                'parent' => 'Admin Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Administrasi',
                'scope' => 'Arsip',
                'status' => 'Active',
                'manager' => 'Nur Aini',
                'staff' => 4,
                'budget' => 200000000,
                'target_kpi' => 'Efisiensi admin',
                'achievement' => '91%',
                'risk' => 'Overload',
                'system_role' => 'Admin',
                'access_rights' => 'Create, Read, Update',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-ADM-02',
                'name' => 'Office Support',
                'parent' => 'Admin Department',
                'level' => 'Sub Divisi',
                'main_function' => 'Operasional kantor',
                'scope' => 'Fasilitas',
                'status' => 'Active',
                'manager' => 'Slamet Riyadi',
                'staff' => 5,
                'budget' => 180000000,
                'target_kpi' => 'Kantor operasional',
                'achievement' => '90%',
                'risk' => 'Kerusakan fasilitas',
                'system_role' => 'Support',
                'access_rights' => 'Read',
                'shift' => 'Normal',
                'operational_hour' => '08:00 - 17:00',
                'location' => 'Office'
            ],
            [
                'code' => 'DIV-STR-01',
                'name' => 'Strategic Planning',
                'parent' => 'Direksi',
                'level' => 'Divisi',
                'main_function' => 'Perencanaan strategis',
                'scope' => 'Analisis bisnis',
                'status' => 'Active',
                'manager' => 'CEO',
                'staff' => 3,
                'budget' => 1000000000,
                'target_kpi' => 'Strategi tahunan',
                'achievement' => 'Tercapai',
                'risk' => 'Kesalahan strategi',
                'system_role' => 'Management',
                'access_rights' => 'Read',
                'shift' => 'Normal',
                'operational_hour' => '09:00 - 17:00',
                'location' => 'Office'
            ]
        ];

        DB::table('divisions')->insert($divisions);
    }
}